# .travis.yml for R projects

language: r
warnings_are_errors: true
sudo: required


cache: apt

notifications:
  slack: n2nplace:po7Zzne5pBkVqO5tV8To2KuA
  email:
    on_success: change
    on_failure: change
  
r_packages:
  - covr
after_success:
  - Rscript -e 'covr::codecov()'
